server.port=8082
spring.application.name=catalogo-service

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo_db
spring.datasource.username=bootcamp_user
spring.datasource.password=bootcamp_password_sec2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Puerto de gestión (opcional, recomendado para producción)
management.server.port=8091

# Exponer el endpoint de Prometheus (y otros si es necesario)
management.endpoints.web.exposure.include=prometheus,health,metrics

# Etiqueta global con el nombre de la aplicación
management.metrics.tags.application=catalogo-service

# -----------------------------------------------------------------
# CONFIGURACIÓN DE OBSERVABILIDAD Y LOGS (LOKI / LOGBACK)
# -----------------------------------------------------------------

# Nivel general de logs de tu aplicación
logging.level.root=INFO
logging.level.com.bootcamp.catalogo=DEBUG

# Opcional: Si quieres ver las consultas SQL detalladas y sus parámetros en formato JSON
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# -----------------------------------------------------------------
# CONFIGURACIÓN DE ACTUATOR / MICROMETER / PROMETHEUS
# -----------------------------------------------------------------

# Detalles completos de salud (Health Check para Readiness/Liveness probes)
management.endpoint.health.show-details=always
management.health.probes.enabled=true

# Habilitar histogramas para medir percentiles de latencia en peticiones HTTP
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# -----------------------------------------------------------------
# CONFIGURACIÓN DE TRAZADO DISTRIBUIDO (JAEGER / OPENTELEMETRY)
# -----------------------------------------------------------------
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://jaeger.herramientas.svc.cluster.local:4318/v1/traces